---
- name: SystemPomiaruCzasu install playbook
  hosts: SPC
  remote_user: "{{run_user}}"
  become: yes
  become_method: sudo
  vars:
    SPC_dir: "/home/dymbol/SPC"
    run_user: "dymbol"
    run_group: "dymbol"

  tasks:
    #for ffmpeg
    - name: install the rpmfusion repo packages
      dnf: name={{ item }}
        state=present
      with_items:
        - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
        - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

    - name: Install required Centos packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - jbigkit-libs
        - python2-olefile
        - zlib
        - zlib-devel
        - gcc
        - redhat-rpm-config
        - git
        - mysql-devel
      when: ansible_distribution == "Centos" and ansible_distribution_major_version > '6'


    - name: Install required Debian packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-dev
        - python3-pip
        - gcc
        - git
        - libsqlclient-dev
      when: ansible_distribution == "Debian"


    - name: Disabling SELINUX
      selinux:
        state: disabled
      when: ansible_distribution == "Centos" and ansible_distribution_major_version > '6'

    - name: disable firewalld
      systemd:
        name: firewalld
        enabled: no
        state: stopped
      when: ansible_distribution == "Centos" and ansible_distribution_major_version > '6'

    - name: Creates SPC directory
      file: path="{{ SPC_dir }}" state=directory

    - name: Get source code from github
      git:
        repo: 'https://github.com/dymbol/SystemPomiaruCzasu.git'
        dest: {{ SPC_dir }}

    - name: Configure SPC
      template:
        src: templates/settings.j2
        dest: "{{ SPC_dir }}/src/SPC/SPC/settings.py"

    - name: install Python requierments
      command: 'pip3 install -r "{{ SPC_dir }}"/src/SPC/requirements.txt'
      become_method: sudo
