---
- name: DGallery install playbook
  hosts: DGallery
  remote_user: "{{run_user}}"
  become: yes
  become_method: sudo
  vars:
    albums_dir: "/home/dymbol/DGallery_albums"
    DGallery_dir: "/home/dymbol/DGallery"
    run_user: "dymbol"
    run_group: "dymbol"

  tasks:
    
    - name: Send compressed code
      copy:
        src: /tmp/DGallery_code.tgz
        dest: /tmp/DGallery_code.tgz
        owner: "{{run_user}}"
        group: "{{run_group}}"
        mode: 0644

    - name: Extract archive
      unarchive:
        src: /tmp/DGallery_code.tgz
        dest: "{{ DGallery_dir }}"
        owner: "{{run_user}}"
        group: "{{run_group}}"

    - name: Configure DGallery
      template:
        src: templates/settings.j2
        dest: "{{ DGallery_dir }}/DymbolGallery/DymbolGallery/settings.py"

    - name: Creates albums directory
      file: path="{{ albums_dir }}" state=directory

    - name: install Python requierments
      command: 'pip install -r "{{ DGallery_dir }}"/DymbolGallery/requirements.txt'
      become_method: sudo
