# Generated by Django 2.0 on 2017-12-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171204_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Race')),
            ],
        ),
        migrations.RemoveField(
            model_name='lap',
            name='race',
        ),
        migrations.AddField(
            model_name='lap',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Track'),
        ),
    ]
