# Generated by Django 2.0 on 2017-12-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_car_car_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_class',
        ),
        migrations.AddField(
            model_name='team',
            name='tclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.CarClass'),
            preserve_default=False,
        ),
    ]
