# Generated by Django 2.0 on 2017-12-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_lap_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='accel_type',
            field=models.CharField(blank=True, choices=[('Turbocharged', 'Turbocharged'), ('Supercharged', 'Supercharged'), ('Electrical', 'Electrical')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_model',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='torque',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
    ]
