# Generated by Django 2.0 on 2017-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20171206_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nick',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_tel',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
