# Generated by Django 2.0 on 2017-12-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20171206_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='loop',
        ),
    ]
