# Generated by Django 2.0 on 2017-12-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20171207_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='result_plus_fee',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='result_taryfa',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
