# Generated by Django 2.0 on 2018-01-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20171207_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='result_plus_fee',
        ),
        migrations.RemoveField(
            model_name='lap',
            name='result_taryfa',
        ),
    ]
